/*
* Copyright (c) 1998-2006 Caucho Technology -- all rights reserved
*
* This file is part of Resin(R) Open Source
*
* Each copy or derived work must preserve the copyright notice and this
* notice unmodified.
*
* Resin Open Source is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* Resin Open Source is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, or any warranty
* of NON-INFRINGEMENT.  See the GNU General Public License for more
* details.
*
* You should have received a copy of the GNU General Public License
* along with Resin Open Source; if not, write to the
*
*   Free Software Foundation, Inc.
*   59 Temple Place, Suite 330
*   Boston, MA 02111-1307  USA
*
* @author Scott Ferguson
*/

package javax.xml.bind;
import javax.xml.stream.*;
import javax.xml.transform.*;
import org.w3c.dom.*;
import java.io.*;
import org.xml.sax.*;
import javax.xml.bind.attachment.*;
import javax.xml.bind.Unmarshaller.*;
import javax.xml.validation.*;
import javax.xml.bind.annotation.adapters.*;
import java.net.*;

/**
 * The Unmarshaller class governs the process of deserializing XML data into
 * newly created Java content trees, optionally validating the XML data as it
 * is unmarshalled. It provides an overloading of unmarshal methods for many
 * different input kinds. Unmarshalling from a File: Unmarshalling from an
 * InputStream: Unmarshalling from a URL: Unmarshalling from a StringBuffer
 * using a javax.xml.transform.stream.StreamSource: Unmarshalling from a
 * org.w3c.dom.Node: Unmarshalling from a javax.xml.transform.sax.SAXSource
 * using a client specified validating SAX2.0 parser: Unmarshalling from a StAX
 * XMLStreamReader: Unmarshalling from a StAX XMLEventReader: Unmarshalling XML
 * Data Unmarshal a root element that is globally declared Unmarshal by
 * Declared Type Unmarshal By Declared Type returned JAXBElement JAXBElement
 * Property Value name xml element name value instanceof declaredType
 * declaredType unmarshal method declaredType parameter scope null (actual
 * scope is unknown) The following is an example of unmarshal by declaredType
 * method. Unmarshal by declaredType from a org.w3c.dom.Node: Support for
 * SAX2.0 Compliant Parsers Validation and Well-Formedness A client application
 * can enable or disable JAXP 1.3 validation mechanism via the
 * setSchema(javax.xml.validation.Schema) API. Sophisticated clients can
 * specify their own validating SAX 2.0 compliant parser and bypass the JAXP
 * 1.3 validation mechanism using the unmarshal(Source) API. Since
 * unmarshalling invalid XML content is defined in JAXB 2.0, the Unmarshaller
 * default validation event handler was made more lenient than in JAXB 1.0.
 * When schema-derived code generated by JAXB 1.0 binding compiler is
 * registered with JAXBContext, the default unmarshal validation handler is
 * DefaultValidationEventHandler and it terminates the marshal operation after
 * encountering either a fatal error or an error. For a JAXB 2.0 client
 * application, there is no explicitly defined default validation handler and
 * the default event handling only terminates the marshal operation after
 * encountering a fatal error. Supported Properties There currently are not any
 * properties required to be supported by all JAXB Providers on Unmarshaller.
 * However, some providers may support their own set of provider specific
 * properties. Unmarshal Event Callbacks 'Class defined' event callback methods
 * allow any JAXB mapped class to specify its own specific callback methods by
 * defining methods with the following method signature: The external listener
 * callback mechanism enables the registration of a Unmarshaller.Listener
 * instance with an setListener(Listener). The external listener receives all
 * callback events, allowing for more centralized processing than per class
 * defined callback methods. The external listener receives events when
 * unmarshalling proces is marshalling to a JAXB element or to JAXB mapped
 * class. The 'class defined' and external listener event callback methods are
 * independent of each other, both can be called for one event. The invocation
 * ordering when both listener callback methods exist is defined in
 * Unmarshaller.Listener.beforeUnmarshal(Object, Object) and
 * Unmarshaller.Listener.afterUnmarshal(Object, Object). An event callback
 * method throwing an exception terminates the current unmarshal process.
 * Since: JAXB1.0 Version: $Revision: 1.32 $ $Date: 2005/08/18 15:18:26 $
 * Author: Ryan Shoemaker, Sun Microsystems, Inc.Kohsuke Kawaguchi, Sun
 * Microsystems, Inc.Joe Fialli, Sun Microsystems, Inc. See Also:JAXBContext,
 * Marshaller, Validator
 */
public interface Unmarshaller {

  /**
   * Gets the adapter associated with the specified type. This is the reverse
   * operation of the method.
   */
  abstract <A extends XmlAdapter> A getAdapter(Class<A> type);

  abstract AttachmentUnmarshaller getAttachmentUnmarshaller();


  /**
   * Return the current event handler or the default event handler if one
   * hasn't been set.
   */
  abstract ValidationEventHandler getEventHandler() throws JAXBException;


  /**
   * Return Unmarshaller.Listener registered with this Unmarshaller.
   */
  abstract Listener getListener();


  /**
   * Get the particular property in the underlying implementation of
   * Unmarshaller. This method can only be used to get one of the standard JAXB
   * defined properties above or a provider specific property. Attempting to
   * get an undefined property will result in a PropertyException being thrown.
   * See .
   */
  abstract Object getProperty(String name) throws PropertyException;


  /**
   * Get the JAXP 1.3 object being used to perform unmarshal-time validation.
   * If there is no Schema set on the unmarshaller, then this method will
   * return null indicating that unmarshal-time validation will not be
   * performed. This method provides replacement functionality for the
   * deprecated isValidating() API as well as access to the Schema object. To
   * determine if the Unmarshaller has validation enabled, simply test the
   * return type for null: boolean isValidating = u.getSchema()!=null;
   */
  abstract Schema getSchema();


  /**
   * Get an unmarshaller handler object that can be used as a component in an
   * XML pipeline. The JAXB Provider can return the same handler object for
   * multiple invocations of this method. In other words, this method does not
   * necessarily create a new instance of UnmarshallerHandler. If the
   * application needs to use more than one UnmarshallerHandler, it should
   * create more than one Unmarshaller.
   */
  abstract UnmarshallerHandler getUnmarshallerHandler();


  /**
   * Deprecated. Indicates whether or not the Unmarshaller is configured to
   * validate during unmarshal operations. This API returns the state of the
   * JAXB Provider's default unmarshal-time validation mechanism. This method
   * is deprecated as of JAXB 2.0 - please use the new getSchema() API.
   */
  abstract boolean isValidating() throws JAXBException;


  /**
   * Associates a configured instance of with this unmarshaller. Every
   * unmarshaller internally maintains a MapClass,XmlAdapter>, which it uses
   * for unmarshalling classes whose fields/methods are annotated with
   * XmlJavaTypeAdapter. This method allows applications to use a configured
   * instance of XmlAdapter. When an instance of an adapter is not given, an
   * unmarshaller will create one by invoking its default constructor.
   */
  abstract <A extends XmlAdapter> void setAdapter(Class<A> type, A adapter);

  /**
   * Associates a configured instance of with this unmarshaller. This is a
   * convenience method that invokes setAdapter(adapter.getClass(),adapter);.
   */
  abstract void setAdapter(XmlAdapter adapter);


  /**
   * Associate a context that resolves cid's, content-id URIs, to binary data
   * passed as attachments. Unmarshal time validation, enabled via
   * setSchema(Schema), must be supported even when unmarshaller is performing
   * XOP processing.
   */
  abstract void setAttachmentUnmarshaller(AttachmentUnmarshaller au);


  /**
   * Allow an application to register a ValidationEventHandler. The
   * ValidationEventHandler will be called by the JAXB Provider if any
   * validation errors are encountered during calls to any of the unmarshal
   * methods. If the client application does not register a
   * ValidationEventHandler before invoking the unmarshal methods, then
   * ValidationEvents will be handled by the default event handler which will
   * terminate the unmarshal operation after the first error or fatal error is
   * encountered. Calling this method with a null parameter will cause the
   * Unmarshaller to revert back to the default event handler.
   */
  abstract void setEventHandler(ValidationEventHandler handler) throws JAXBException;


  /**
   * Register unmarshal event callback Unmarshaller.Listener with this
   * Unmarshaller. There is only one Listener per Unmarshaller. Setting a
   * Listener replaces the previous set Listener. One can unregister current
   * Listener by setting listener to null.
   */
  abstract void setListener(Listener listener);


  /**
   * Set the particular property in the underlying implementation of
   * Unmarshaller. This method can only be used to set one of the standard JAXB
   * defined properties above or a provider specific property. Attempting to
   * set an undefined property will result in a PropertyException being thrown.
   * See .
   */
  abstract void setProperty(String name, Object value) throws PropertyException;


  /**
   * Specify the JAXP 1.3 object that should be used to validate subsequent
   * unmarshal operations against. Passing null into this method will disable
   * validation. This method replaces the deprecated setValidating(boolean)
   * API. Initially this property is set to null.
   */
  abstract void setSchema(Schema schema);


  /**
   * Deprecated. Specifies whether or not the default validation mechanism of
   * the Unmarshaller should validate during unmarshal operations. By default,
   * the Unmarshaller does not validate. This method may only be invoked before
   * or after calling one of the unmarshal methods. This method only controls
   * the JAXB Provider's default unmarshal-time validation mechanism - it has
   * no impact on clients that specify their own validating SAX 2.0 compliant
   * parser. Clients that specify their own unmarshal-time validation mechanism
   * may wish to turn off the JAXB Provider's default validation mechanism via
   * this API to avoid "double validation". This method is deprecated as of
   * JAXB 2.0 - please use the new setSchema(javax.xml.validation.Schema) API.
   */
  abstract void setValidating(boolean validating) throws JAXBException;


  /**
   * Unmarshal XML data from the specified file and return the resulting
   * content tree. Implements Unmarshal Global Root Element.
   */
  abstract Object unmarshal(File f) throws JAXBException;


  /**
   * Unmarshal XML data from the specified SAX InputSource and return the
   * resulting content tree. Implements Unmarshal Global Root Element.
   */
  abstract Object unmarshal(InputSource source) throws JAXBException;


  /**
   * Unmarshal XML data from the specified InputStream and return the resulting
   * content tree. Validation event location information may be incomplete when
   * using this form of the unmarshal API. Implements Unmarshal Global Root
   * Element.
   */
  abstract Object unmarshal(InputStream is) throws JAXBException;


  /**
   * Unmarshal global XML data from the specified DOM tree and return the
   * resulting content tree. Implements Unmarshal Global Root Element.
   */
  abstract Object unmarshal(Node node) throws JAXBException;


  /**
   * Unmarshal XML data by JAXB mapped declaredType and return the resulting
   * content tree. Implements Unmarshal by Declared Type
   */
  abstract <T> JAXBElement<T> unmarshal(Node node, Class<T> declaredType)
      throws JAXBException;


  /**
   * Unmarshal XML data from the specified Reader and return the resulting
   * content tree. Validation event location information may be incomplete when
   * using this form of the unmarshal API, because a Reader does not provide
   * the system ID. Implements Unmarshal Global Root Element.
   */
  abstract Object unmarshal(Reader reader) throws JAXBException;


  /**
   * Unmarshal XML data from the specified XML Source and return the resulting
   * content tree. Implements Unmarshal Global Root Element. SAX 2.0 Parser
   * Pluggability A client application can choose not to use the default parser
   * mechanism supplied with their JAXB provider. Any SAX 2.0 compliant parser
   * can be substituted for the JAXB provider's default mechanism. To do so,
   * the client application must properly configure a SAXSource containing an
   * XMLReader implemented by the SAX 2.0 parser provider. If the XMLReader has
   * an org.xml.sax.ErrorHandler registered on it, it will be replaced by the
   * JAXB Provider so that validation errors can be reported via the
   * ValidationEventHandler mechanism of JAXB. If the SAXSource does not
   * contain an XMLReader, then the JAXB provider's default parser mechanism
   * will be used. This parser replacement mechanism can also be used to
   * replace the JAXB provider's unmarshal-time validation engine. The client
   * application must properly configure their SAX 2.0 compliant parser to
   * perform validation (as shown in the example above). Any
   * SAXParserExceptions encountered by the parser during the unmarshal
   * operation will be processed by the JAXB provider and converted into JAXB
   * ValidationEvent objects which will be reported back to the client via the
   * ValidationEventHandler registered with the Unmarshaller. Note: specifying
   * a substitute validating SAX 2.0 parser for unmarshalling does not
   * necessarily replace the validation engine used by the JAXB provider for
   * performing on-demand validation. The only way for a client application to
   * specify an alternate parser mechanism to be used during unmarshal is via
   * the unmarshal(SAXSource) API. All other forms of the unmarshal method
   * (File, URL, Node, etc) will use the JAXB provider's default parser and
   * validator mechanisms.
   */
  abstract Object unmarshal(Source source) throws JAXBException;


  /**
   * Unmarshal XML data from the specified XML Source by declaredType and
   * return the resulting content tree. Implements Unmarshal by Declared Type
   * See SAX 2.0 Parser Pluggability
   */
  abstract <T> JAXBElement<T> unmarshal(Source node, Class<T> declaredType)
      throws JAXBException;

  /**
   * Unmarshal XML data from the specified URL and return the resulting content
   * tree. Implements Unmarshal Global Root Element.
   */
  abstract Object unmarshal(URL url) throws JAXBException;


  /**
   * Unmarshal XML data from the specified pull parser and return the resulting
   * content tree. This method is an Unmarshal Global Root method. This method
   * assumes that the parser is on a START_DOCUMENT or START_ELEMENT event.
   * Unmarshalling will be done from this start event to the corresponding end
   * event. If this method returns successfully, the reader will be pointing at
   * the token right after the end event.
   */
  abstract Object unmarshal(XMLEventReader reader) throws JAXBException;


  /**
   * Unmarshal root element to JAXB mapped declaredType and return the
   * resulting content tree. This method implements unmarshal by declaredType.
   * This method assumes that the parser is on a START_DOCUMENT or
   * START_ELEMENT event. Unmarshalling will be done from this start event to
   * the corresponding end event. If this method returns successfully, the
   * reader will be pointing at the token right after the end event.
   */
  abstract <T> JAXBElement<T> unmarshal(XMLEventReader xmlEventReader,
                                        Class<T> declaredType)
      throws JAXBException;


  /**
   * Unmarshal XML data from the specified pull parser and return the resulting
   * content tree. Implements Unmarshal Global Root Element. This method
   * assumes that the parser is on a START_DOCUMENT or START_ELEMENT event.
   * Unmarshalling will be done from this start event to the corresponding end
   * event. If this method returns successfully, the reader will be pointing at
   * the token right after the end event.
   */
  abstract Object unmarshal(XMLStreamReader reader) throws JAXBException;


  /**
   * Unmarshal root element to JAXB mapped declaredType and return the
   * resulting content tree. This method implements unmarshal by declaredType.
   * This method assumes that the parser is on a START_DOCUMENT or
   * START_ELEMENT event. Unmarshalling will be done from this start event to
   * the corresponding end event. If this method returns successfully, the
   * reader will be pointing at the token right after the end event.
   */
  abstract <T> JAXBElement<T> unmarshal(XMLStreamReader xmlStreamReader,
                                        Class<T> declaredType)
      throws JAXBException;

  /**
   * Since: JAXB2.0
   */
  public static abstract class Listener {
    public Listener()
    {
      throw new UnsupportedOperationException();
    }


    /**
     * Callback method invoked after unmarshalling XML data into target. This
     * method is invoked after all the properties (except IDREF) are
     * unmarshalled into target, but before target is set into its parent
     * object. Note that if the class of target defines its own afterUnmarshal
     * method, the class specific callback method is invoked before this method
     * is invoked.
     */
    public void afterUnmarshal(Object target, Object parent)
    {
      throw new UnsupportedOperationException();
    }


    /**
     * Callback method invoked before unmarshalling into target. This method is
     * invoked immediately after target was created and before the
     * unmarshalling of this object begins. Note that if the class of target
     * defines its own beforeUnmarshal method, the class specific callback
     * method is invoked before this method is invoked.
     */
    public void beforeUnmarshal(Object target, Object parent)
    {
      throw new UnsupportedOperationException();
    }

  }
}

