/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.caucho.netbeans.ide.ui;

import com.caucho.netbeans.ide.AddInstanceIterator;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public final class AddServerVisualPanel extends JPanel {
  private AddInstanceIterator _addServer;
  private AddServerLocationPanel _wizardPanel;

  AddServerVisualPanel(AddInstanceIterator addServer, 
                       AddServerLocationPanel wizardPanel)
  {
    initComponents();

    _addServer = addServer;
    _wizardPanel = wizardPanel;
    
    this.jTextField1.setText(addServer.getResinHome());

    this.jTextField1.getDocument().addDocumentListener(new DocumentListener() {
	public void changedUpdate(DocumentEvent e)
	{
	  _wizardPanel.stateChanged(new ChangeEvent(this));
	}
	
	public void insertUpdate(DocumentEvent e)
	{
	  _wizardPanel.stateChanged(new ChangeEvent(this));
	}
	
	public void removeUpdate(DocumentEvent e)
	{
	  _wizardPanel.stateChanged(new ChangeEvent(this));
	}
      });
  }

  public String getResinHome()
  {
    return this.jTextField1.getText().trim();
  }

  @Override
  public String getName()
  {
    return "Set Resin Home";
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Resin Home");

    jTextField1.setText("jTextField1");

    org.openide.awt.Mnemonics.setLocalizedText(jButton1, "Browse");
    jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton1MouseClicked(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Resin Home Location");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(jLabel1)
            .add(28, 28, 28)
            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(18, 18, 18)
            .add(jButton1))
          .add(jLabel2))
        .addContainerGap(53, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabel2)
        .add(31, 31, 31)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jLabel1)
          .add(jButton1))
        .addContainerGap(219, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    String loc = browseResinHome();
    
    if (loc != null && ! "".equals(loc))
      this.jTextField1.setText(loc);
  }//GEN-LAST:event_jButton1MouseClicked
    
  private String browseResinHome()
  {
    String loc = null;
    JFileChooser chooser = getResinHomeChooser();
    int ret = chooser.showDialog(SwingUtilities.getWindowAncestor(this),
				 "Choose Resin Home");
        
    if (ret == JFileChooser.APPROVE_OPTION)
      return chooser.getSelectedFile().getAbsolutePath();
    else
      return null;
  }
    
  private JFileChooser getResinHomeChooser()
  {
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Select Resin Home");
    chooser.setDialogType(JFileChooser.CUSTOM_DIALOG);

    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setApproveButtonMnemonic('C');
    chooser.setMultiSelectionEnabled(false);
    chooser.setApproveButtonToolTipText("Chooser");

    chooser.getAccessibleContext().setAccessibleName("Chooser");
    chooser.getAccessibleContext().setAccessibleDescription("Chooser");

    chooser.setSelectedFile(new File(getResinHome()));

    return chooser;
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}

