/**
 * object interface generated by Resin-EE doclet.
 * on Sun, 23 Mar 2003 20:24:31 -0800 (PST)
 */

package example;

public interface Teacher
  extends javax.ejb.EJBLocalObject {

  public java.lang.String getName();

  public example.Course getCourse();
}
