/**
 * home interface generated by Resin-EE doclet.
 * on Sun, 23 Mar 2003 20:24:31 -0800 (PST)
 */

package example;

public interface TeacherHome
  extends javax.ejb.EJBLocalHome {

  public example.Teacher findByPrimaryKey(java.lang.String key)
    throws javax.ejb.FinderException;
}
