/**
 * home interface generated by Resin-EE doclet.
 * on Thu, 27 Mar 2003 20:11:34 -0800 (PST)
 */

package example;

public interface CourseHome
  extends javax.ejb.EJBLocalHome {

  public example.Course findByPrimaryKey(java.lang.String key)
    throws javax.ejb.FinderException;
}
