/*
 * Copyright (c) 1998-2012 Caucho Technology -- all rights reserved
 *
 * @author Scott Ferguson
 */

package com.caucho.quercus.expr;

import com.caucho.quercus.env.Env;
import com.caucho.quercus.env.Value;
import com.caucho.quercus.gen.AnalyzeInfo;
import com.caucho.quercus.gen.PhpWriter;

import java.io.IOException;

/**
 * Represents an expression generated by the create routines.
 */
public class JavaCodeExprPro extends Expr
  implements ExprPro
{
  private String _code;

  public JavaCodeExprPro(String code)
  {
    _code = code;
  }

  public Value eval(Env env)
  {
    throw new UnsupportedOperationException();
  }

  public ExprGenerator getGenerator()
  {
    return GENERATOR;
  }

  private ExprGenerator GENERATOR = new ExprGenerator(getLocation()) {
      public ExprType analyze(AnalyzeInfo info)
      {
	return ExprType.VALUE;
      }
      
      public void generate(PhpWriter out)
	throws IOException
      {
	out.print(_code);
      }
    };
}

