/**
 * home interface generated by Resin-EE doclet.
 * on Thu, 27 Mar 2003 19:58:15 -0800 (PST)
 */

package example;

public interface CourseHome
  extends javax.ejb.EJBLocalHome {

  public example.Course findByPrimaryKey(java.lang.String key)
    throws javax.ejb.FinderException;

  public java.util.Collection findAll() throws javax.ejb.FinderException;
}
