/*
 * Generated by Resin-3.0.s040908 (built Thu, 09 Sep 2004 02:24:43 PDT)
 */

package example;

public class House__ResinExt extends example.House implements com.caucho.amber.entity.Entity {
  /*
   * Generated by Resin Amber
   * 3.0.s040908
   */
  private static final java.util.logging.Logger __caucho_log = java.util.logging.Logger.getLogger("example.House");

  protected transient com.caucho.amber.type.EntityType __caucho_home;
  public transient com.caucho.amber.entity.EntityItem __caucho_item;
  protected transient com.caucho.amber.connection.AmberConnectionImpl __caucho_session;
  protected transient int __caucho_state;
  protected transient long __caucho_loadMask;
  protected transient long __caucho_dirtyMask;
  protected transient long __caucho_updateMask;

  public void __caucho_setPrimaryKey(Object key)
  {
    setId(((Number) key).intValue());
  }

  public Object __caucho_getPrimaryKey()
  {
    return new Integer(getId());
  }

  public void __caucho_setConnection(com.caucho.amber.connection.AmberConnectionImpl aConn)
  {
    __caucho_session = aConn;
  }

  public void __caucho_expire()
  {
    __caucho_loadMask = 0L;
