/**
 * home interface generated by Resin-EE doclet.
 * on Fri, 09 May 2003 16:49:26 -0700 (PDT)
 */

package example;

public interface CourseHome
  extends javax.ejb.EJBLocalHome {

  public example.Course findByPrimaryKey(java.lang.String key)
    throws javax.ejb.FinderException;

  public java.util.Collection findAll() throws javax.ejb.FinderException;

  public example.Course create(java.lang.String courseId, java.lang.String instructor)
    throws javax.ejb.CreateException;
}
