/**
 * object interface generated by Resin-EE doclet.
 * on Thu, 27 Mar 2003 20:11:34 -0800 (PST)
 */

package example;

public interface Course
  extends javax.ejb.EJBLocalObject {

  public java.lang.String getId();

  public void setId(java.lang.String courseId);

  public java.lang.String getInstructor();

  public void setInstructor(java.lang.String instructor);

  public void swap(example.Course course);
}
