/*
 * Copyright (c) 1998-2007 Caucho Technology -- all rights reserved
 *
 * This file is part of Resin(R) Open Source
 *
 * Each copy or derived work must preserve the copyright notice and this
 * notice unmodified.
 *
 * Resin Open Source is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Resin Open Source is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, or any warranty
 * of NON-INFRINGEMENT.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Resin Open Source; if not, write to the
 *
 *   Free Software Foundation, Inc.
 *   59 Temple Place, Suite 330
 *   Boston, MA 02111-1307  USA
 *
 * @author Sam
 */


package com.caucho.netbeans.customizer;

import javax.swing.*;
import java.awt.*;

/**
 * General customizer tab
 */
public class CustomizerGeneral
  extends javax.swing.JPanel
{

  private CustomizerDataSupport custData;

  /**
   * Creates new form CustomizerGeneral
   */
  public CustomizerGeneral(CustomizerDataSupport custData)
  {
    this.custData = custData;
    initComponents();

    // work-around for jspinner incorrect fonts
    JTextField serverPortSpinnerTextField
      = ((JSpinner.NumberEditor) serverPortSpinner.getEditor()).getTextField();
    Font font = rootTextField.getFont();
    serverPortSpinnerTextField.setFont(font);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
        // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
        private void initComponents()
        {
                rootLabel = new javax.swing.JLabel();
                baseLabel = new javax.swing.JLabel();
                rootTextField = new javax.swing.JTextField();
                baseTextField = new javax.swing.JTextField();
                serverPortLabel = new javax.swing.JLabel();
                serverPortSpinner = new javax.swing.JSpinner();
                jLabel4 = new javax.swing.JLabel();

                rootLabel.setLabelFor(rootTextField);
                rootLabel.setText(org.openide.util.NbBundle.getMessage(CustomizerGeneral.class, "LBL_ResinRoot"));

                baseLabel.setLabelFor(baseTextField);
                baseLabel.setText(org.openide.util.NbBundle.getMessage(CustomizerGeneral.class, "LBL_ResinBase"));

                rootTextField.setColumns(20);
                rootTextField.setDocument(custData.getResinRootModel());
                rootTextField.setEditable(false);

                baseTextField.setColumns(20);
                baseTextField.setDocument(custData.getResinBaseModel());
                baseTextField.setEditable(false);

                serverPortLabel.setLabelFor(serverPortSpinner);
                serverPortLabel.setText(org.openide.util.NbBundle.getMessage(CustomizerGeneral.class, "LBL_ServerPort"));

                serverPortSpinner.setModel(custData.getServerPortModel());
                serverPortSpinner.setEditor(new JSpinner.NumberEditor(serverPortSpinner, "#"));

                jLabel4.setText(org.openide.util.NbBundle.getMessage(CustomizerGeneral.class, "TXT_NoteChangesTakeAffect"));

                org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                                .add(serverPortLabel)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(serverPortSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(rootLabel)
                                                        .add(baseLabel))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, baseTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                                        .add(rootTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                                        .add(jLabel4))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(rootLabel)
                                        .add(rootTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(baseLabel)
                                        .add(baseTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(17, 17, 17)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(serverPortLabel)
                                        .add(serverPortSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 87, Short.MAX_VALUE)
                                .add(jLabel4)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel baseLabel;
        private javax.swing.JTextField baseTextField;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel rootLabel;
        private javax.swing.JTextField rootTextField;
        private javax.swing.JLabel serverPortLabel;
        private javax.swing.JSpinner serverPortSpinner;
        // End of variables declaration//GEN-END:variables

}
