/*
 * Copyright (c) 1998-2007 Caucho Technology -- all rights reserved
 *
 * This file is part of Resin(R) Open Source
 *
 * Each copy or derived work must preserve the copyright notice and this
 * notice unmodified.
 *
 * Resin Open Source is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Resin Open Source is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, or any warranty
 * of NON-INFRINGEMENT.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Resin Open Source; if not, write to the
 *
 *   Free Software Foundation, Inc.
 *   59 Temple Place, Suite 330
 *   Boston, MA 02111-1307  USA
 *
 * @author Sam
 */


package com.caucho.netbeans.customizer;

import org.netbeans.api.java.platform.PlatformsCustomizer;

public class CustomizerPlatform
  extends javax.swing.JPanel
{

  private final CustomizerDataSupport custData;

  /**
   * Creates new form CustomizerPlatform
   */
  public CustomizerPlatform(CustomizerDataSupport custData)
  {
    this.custData = custData;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jCheckBox1 = new javax.swing.JCheckBox();
    jLabel4 = new javax.swing.JLabel();

    org.openide
      .awt
      .Mnemonics
      .setLocalizedText(jLabel1,
                        org.openide.util.NbBundle.getMessage(CustomizerPlatform.class,
                                                             "TXT_JVM"));

    org.openide
      .awt
      .Mnemonics
      .setLocalizedText(jLabel2,
                        org.openide.util.NbBundle.getMessage(CustomizerPlatform.class,
                                                             "TXT_VMOptions"));

    jComboBox1.setModel(custData.getJvmModel());

    jTextField1.setDocument(custData.getJavaOptsModel());

    org.openide
      .awt
      .Mnemonics
      .setLocalizedText(jButton1,
                        org.openide.util.NbBundle.getMessage(CustomizerPlatform.class,
                                                             "TXT_ManagePlatforms"));
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });

    jLabel3.setText(org.openide.util.NbBundle.getMessage(CustomizerPlatform.class,
                                                         "TXT_VMOptionsEG"));

    org.openide
      .awt
      .Mnemonics
      .setLocalizedText(jCheckBox1,
                        org.openide.util.NbBundle.getMessage(CustomizerPlatform.class,
                                                             "LBL_HttpProxy"));
    jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,
                                                                     0,
                                                                     0,
                                                                     0));
    jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jCheckBox1.setModel(custData.getProxyModel());

    jLabel4.setText(org.openide.util.NbBundle.getMessage(CustomizerPlatform.class,
                                                         "TXT_NoteChangesTakeAffect"));

    org.jdesktop.layout.GroupLayout layout
      = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jLabel1)
          .add(jLabel2))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
          .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel3)
            .add(jComboBox1, 0, 219, Short.MAX_VALUE))
          .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
          .add(jButton1)
          .add(12, 12, 12))
        .add(layout.createSequentialGroup()
        .add(jTextField1,
             org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
             380,
             Short.MAX_VALUE)
        .addContainerGap())))
      .add(layout.createSequentialGroup()
        .add(12, 12, 12)
        .add(jLabel4)
        .addContainerGap(90, Short.MAX_VALUE))
      .add(layout.createSequentialGroup()
      .add(12, 12, 12)
      .add(jCheckBox1)
      .addContainerGap(332, Short.MAX_VALUE)));
    layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
      .addContainerGap()
      .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
        .add(jLabel1)
        .add(jButton1)
        .add(jComboBox1,
             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
             org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
      .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
      .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
        .add(jLabel2)
        .add(jTextField1,
             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
             org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
      .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
      .add(jLabel3)
      .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
      .add(jCheckBox1)
      .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED,
                       100,
                       Short.MAX_VALUE)
      .add(jLabel4)
      .addContainerGap()));
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
  {//GEN-FIRST:event_jButton1ActionPerformed
    PlatformsCustomizer.showCustomizer(null);
    custData.loadJvmModel();
  }//GEN-LAST:event_jButton1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables

}
