/**
 * object interface generated by Resin-EE doclet.
 * on Fri, 09 May 2003 16:49:26 -0700 (PDT)
 */

package example;

public interface Course
  extends javax.ejb.EJBLocalObject {

  public java.lang.String getId();

  public java.lang.String getInstructor();
}
