/**
 * home interface generated by Resin-EE doclet.
 * on Fri, 14 Feb 2003 16:27:20 -0800 (PST)
 */

package example;

public interface TestHome
  extends javax.ejb.EJBLocalHome {

  public example.TestLocal findByPrimaryKey(java.lang.String key)
    throws javax.ejb.FinderException;

  public java.util.Collection findAll() throws javax.ejb.FinderException;
  public example.TestLocal create(java.lang.String courseId, java.lang.String instructor)
    throws javax.ejb.CreateException;
}
