/**
 * object interface generated by Resin-EE doclet.
 * on Fri, 14 Feb 2003 16:27:20 -0800 (PST)
 */

package example;

public interface TestLocal
  extends javax.ejb.EJBLocalObject {

  public java.lang.String getId();

  public java.lang.String getInstructor();
}
