#!/bin/sh

useradd -d /nonexistent -s /bin/false -M resin 2> /dev/null

chown -R resin.resin /var/resin
chown -R resin.resin /var/log/resin

if [ -x "/etc/init.d/resin" ]; then
	update-rc.d resin defaults 90 10 >/dev/null 2>/dev/null
	if [ -x "`which service 2>/dev/null`" ]; then
		service resin stop 2>/dev/null 1>/dev/null
		service resin start
	else
		/etc/init.d/resin stop 2>/dev/null 1>/dev/null
		/etc/init.d/resin start
	fi
fi

echo 
echo "-----------------------------------------------------------------------"
echo 
echo 
echo " You have installed Resin Open Source.  If you would like to upgrade to"
echo " Resin Professional, please visit http://caucho.com"
echo 
echo 
echo "-----------------------------------------------------------------------"
