/**
 * object interface generated by Resin-EE doclet.
 * on Thu, 27 Mar 2003 21:21:24 -0800 (PST)
 */

package example;

public interface Course
  extends javax.ejb.EJBLocalObject {

  public java.lang.String getId();

  public java.lang.String getInstructor();
}
